DRAFT commit
DANS-KNAW/dd-pre-publish-workflow pull request #1
Opened 2020-06-15 14:13 UTC by ChrisMuller80

DRAFT version of Dataverse Dans workflow service

repo                       | PR                | note
-------------------------- | ----------------- | ----
easy-                      | [PR#](PRlink)     | ..

2020-06-19 13:32 UTC, jo-pol requested changes

2020-06-19 13:32 UTC, jo-pol commented on .github/CODEOWNERS
> +
I suppose you should have replaced with @DANS-KNAW/dataversedans

The archetype also missed some lines for [PULL_REQUEST_TEMPLATE](https://github.com/DANS-KNAW/dd-easy-worflows-poc/blob/master/.github/PULL_REQUEST_TEMPLATE.md)
It should trigger the review process with notifications and get it on an overview like for [EASY](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+team%3ADANS-KNAW%2Feasy)



Its content should become something like
```
Fixes EASY-

* 
* 
* 

#### Where should the reviewer @DANS-KNAW/dataversedans start?

#### How should this be manually tested?

#### Related pull requests on github

repo                       | PR                | note
-------------------------- | ----------------- | ----
easy-                      | [PR#](PRlink)     | ..

```

2020-06-23 08:05 UTC, jo-pol requested changes

2020-06-23 08:05 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocApp.scala
> +    var json = JsonMethods.parse(jsonString) \ "data"
please avoid `var`

2020-06-23 08:05 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocApp.scala
> +    if (access.equals("Open Access")) {
Please use the scala way to compare objects
```suggestion
    if (access == "Open Access") {
```

2020-06-23 08:05 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocApp.scala
> +      if (!licenseFromMetadata.equalsIgnoreCase("CC0-1.0")) {
idem
```suggestion
      if (!licenseFromMetadata.toUpperCase == "CC0-1.0") {
```

2020-06-23 08:05 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocApp.scala
> +    }
I'm not familiar with `json.transformField` but can't we rewrite this into something like below? (there is still a logical expression to extract into a val) 

Please provide unit tests.

```
    val isOpen = access == "Open Access"
    val isCC0 = licenseFromMetadata.toUpperCase == "CC0-1.0"
    json = json.transformField {
      case JField("license", JString(_)) if (isOpen && !isCC0) || !isOpen => ("license", JString("NONE"))
      case JField("termsOfUse", JString(_)) if (isOpen && !isCC0) || !isOpen => ("termsOfUse", JString(licenseFromMetadata))
      case JField("termsOfUse", JString(_)) if !isOpen => ("termsOfUse", JString("DANS LICENSE"))
    }
```

2020-06-23 08:05 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocApp.scala
> +  def updateMetadata(datasetIdentifier: String, invocationId: String, metadata: String): Unit = {
```suggestion
  private def updateMetadata(datasetIdentifier: String, invocationId: String, metadata: String): Unit = {
```

2020-06-23 08:05 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocApp.scala
> +  def updateLicense(jsonString: String): String = {
```suggestion
  private def updateLicense(jsonString: String): String = {
```

2020-06-23 08:05 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocApp.scala
> +  def getDatasetJson(datasetIdentifier: String): String = {
```suggestion
  private def getDatasetJson(datasetIdentifier: String): String = {
```

2020-06-23 12:01 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocApp.scala
> +    val datasetJson =
![image](https://user-images.githubusercontent.com/10553630/85390761-911c1c00-b549-11ea-953c-800e99a01637.png)

2020-06-23 12:01 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocApp.scala
> +    resume.start()
inline here too

2020-06-23 12:01 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocApp.scala
> +  def updateLicense(jsonString: String): String = {
For your first scala unit tests you might want to keep this public. The unit tests then can become something like 
```
"updateLicense" should "succeed" in {
   new DdEasyWorkflowsPocApp(null).updateLicense("""..."".") shouldBe """..."""
}
it should "fail" in {
  the[...Exception] thrownBy ... shoulBe ...Eception(...)
}
```

2020-06-23 12:01 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocServlet.scala
> +
```suggestion
import nl.knaw.dans.lib.error._
import scala.util.Try

```

2020-06-23 12:01 UTC, jo-pol commented on src/main/scala/nl.knaw.dans.dd.wf/DdEasyWorkflowsPocServlet.scala
> +    app.doWorkflow(invocationId, datasetIdentifier)
Minimal error handling
```suggestion
    (for {
      requestBodyJson <- Try(JsonMethods.parse(request.body))
      invocationId = (requestBodyJson \ "invocationId").extract[String]
      datasetIdentifier = (requestBodyJson \ "globalId").extract[String]
      _ <- Try(app.doWorkflow(invocationId, datasetIdentifier))
    } yield Ok())
      .doIfFailure {
        case e => logger.error(e.getMessage, e)
      }.getOrElse(InternalServerError())
```

Of course a json parse error should become a bad requests etc, but after all it's a proof of concept.

2020-06-25 07:22 UTC, jo-pol commented on README.md
> +For documentation see: https://dans-knaw.github.io/easy-module-archetype
```suggestion
For documentation see: https://dans-knaw.github.io/dd-easy-worflows-poc
```

2020-06-26 14:14 UTC, janvanmansum reviewed
A POC does *not* have to have very clean code (it is not prohibited either,
of course), but is *should* be easy to run the POC. How to do that?

* Make sure it builds (now there are some unit test failing)
* Document *all* the steps for running the POC. 
  * How to start the Dataverse instance. You don't have to describe it again if
    it is already documented, of course. In this case Menko described that. But
    do refer where it is documented.
  * (I guess the API token should always be necessary, although to my surprise it
    wasn't. Maybe we should look into that.)
  * It didn't work on my machine, so I should have taken some additional 
    step.

2020-10-26 08:11 UTC, jo-pol commented
I'm afraid a `k` is missing in the name of the project.

2020-11-18 07:35 UTC, merged